# Generated by Django 4.1.5 on 2023-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_listing_image1_listing_image2_listing_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_guide_listing',
            field=models.BooleanField(default=False),
        ),
    ]
