# Generated by Django 4.1.5 on 2023-06-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_listing_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highlights',
            field=models.CharField(blank=True, choices=[('credit_cards', 'Accepts Credit Cards'), ('smoking', 'Smoking Allowed'), ('bike_parking', 'Bike Parking'), ('street_parking', 'Street Parking'), ('wireless_internet', 'Wireless Internet'), ('alcohol', 'Alcohol')], max_length=50),
        ),
    ]
