# Generated by Django 4.1.5 on 2023-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_listing_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highlights',
        ),
        migrations.AddField(
            model_name='listing',
            name='highlights',
            field=models.ManyToManyField(to='myapp.highlight'),
        ),
    ]
