# Generated by Django 4.1.7 on 2023-06-21 09:09

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_review_customer_alter_review_listing_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image1',
            field=models.ImageField(upload_to=myapp.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image2',
            field=models.ImageField(upload_to=myapp.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image3',
            field=models.ImageField(upload_to=myapp.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image4',
            field=models.ImageField(upload_to=myapp.models.get_image_filename),
        ),
    ]
