# Generated by Django 4.1.7 on 2023-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_listing_email_alter_listing_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcategory',
            name='svg_img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
