# Generated by Django 4.1.7 on 2023-06-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='guides',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
