# Generated by Django 4.1.7 on 2023-06-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0021_alter_guides_image1_guidesreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='o_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.listing'),
        ),
        migrations.CreateModel(
            name='Message_Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('guide_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.guides')),
            ],
        ),
    ]
