# Generated by Django 4.1.7 on 2023-06-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_messages_o_receiver_message_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_guide',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
