# Generated by Django 4.1.7 on 2023-06-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_message_guide_viewed_messages_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_guide',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
