# Generated by Django 4.1.7 on 2023-06-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_message_guide_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_guide',
            name='o_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.listing'),
        ),
    ]
