# Generated by Django 4.1.7 on 2023-06-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_message_guide_sentby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_guide',
            name='sentby',
            field=models.CharField(max_length=10),
        ),
    ]
