# Generated by Django 4.1.7 on 2023-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_message_guide_sentby'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
