# Generated by Django 4.1.7 on 2023-06-23 15:37

from django.db import migrations, models
import mina.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to=mina.models.path_filename)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
