# Generated by Django 4.1.7 on 2023-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='image1',
            field=models.ImageField(upload_to='homeslider/'),
        ),
    ]
